# Generated by Django 5.0.7 on 2024-07-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursecategory_assignment_course_category_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='lesson_files/'),
        ),
    ]
