# Generated by Django 5.0.7 on 2024-08-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cart_studentprofile_studentactivitylog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='course',
        ),
    ]
